# Generated by Django 3.1.7 on 2021-03-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_de_inclusao',
            field=models.DateField(auto_now=True),
        ),
    ]
